### ISSUE TITLE
Check potential error in tutorial

### ISSUE THREAD

**Issue by collisilva** [azizka/IUCNN#13]
Hey @azizka & al.

I was trying to follow your tutorial of IUCN using the default data of the package, and there is a passage in the code that I believe needs to be corrected:

`#train the model`
`train_iucnn(x = features,
            labels = training_labels)`

`# Prepare training labels`
`labels_train <- prepare_labels(training_labels)`

This way isn't working for me. But when I first created the `labels_train` object and than used `train_iucnn` function, and `labels = labels_train`, it worked.

cheers

**Comment by azizka** [comment]
Thanks fixed in the latest version
