### ISSUE TITLE
Bug in function prep_labels

### ISSUE THREAD

**Issue by sandro-unibe** [azizka/IUCNN#31]
If one has data with a column that harbors labels but the column has another name (“status” in my case), he can specify the argument “labels” in the function prep_labels.
But this has an influence on the output of the function. Namely there is the variable `myLabels$lookup$labels` which then is called `myLabels$lookup$status`. This restricts further automated processing. Namely after training the model the function predict_iucnn expects the model to harbor the variable `model$input_data$lookup.labels` which is named `model$input_data$lookup.status` instead and thus an error is thrown.
This problem could possibly be solved by adapting the function prep_labels on line 35 from:
`names(lookup) <- c(labels, "lab.num.z")`
to:
`names(lookup) <- c("labels", "lab.num.z")`

**Comment by azizka** [comment]
Hi, thanks! Implemented as suggested. OK?

**Comment by sandro-unibe** [comment]
No, I was wrong. Changing the line didn't solve the problem because then in the following line the `left_join(lookup, by = labels)` doesn't know which columns to join since they now differ. I solved the problem for myself by changing the names of `lookup` just before the list for the output is built:
`names(lookup) <- c("labels", "lab.num.z")`
`out <- list(labels = out, lookup = lookup)`

**Comment by azizka** [comment]
OK, should be fixed now.
